# https://github.com/marketplace/actions/github-action-for-yarn

name: Run Tests

on:
  push:

jobs:
  build:
    name: Test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [22.x]

    steps:
      - uses: actions/checkout@v3
        name: Checkout
      - uses: borales/actions-yarn@v3.0.0
        name: Install Dependencies
        with:
            cmd: install
      - uses: borales/actions-yarn@v3.0.0
        name: Test
        with:
          cmd: test
      - name: Generate Docs
        uses: borales/actions-yarn@v3.0.0
        # if: github.ref == 'refs/heads/main'
        with:
          cmd: doc
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v4
        if: github.ref == 'refs/heads/main'
        with:
          # github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: ./docs
