name: Run Tests

on:
  push:

permissions:
  contents: write

jobs:
  build:
    name: Test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [22.x, 24.x]

    steps:
      - uses: actions/checkout@v4
        name: Checkout
      - uses: actions/setup-node@v4
        name: Setup Node
        with:
          node-version: ${{ matrix.node-version }}
          cache: npm
      - name: Install Dependencies
        run: npm ci
      - name: Type Check
        run: npm run typecheck
      - name: Test
        run: npm test
      - name: Build
        run: npm run build
      - name: Generate Docs
        if: github.ref == 'refs/heads/master' && matrix.node-version == '22.x'
        run: npm run doc
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v4
        if: github.ref == 'refs/heads/master' && matrix.node-version == '22.x'
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: ./docs
